<a href="https://colab.research.google.com/github/woongjoonchoi/DeepLearningPaper-Reproducing/blob/master/Vgg/grad_accum_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
# loss = nn.MSELoss()
# input = torch.randn(3, 5, requires_grad=True)
# target = torch.randn(3, 5)
# output = loss(input, target)
# output.backward()

In [28]:
line = torch.nn.Linear(1,1)

In [45]:
c = torch.tensor([1],dtype=torch.float32).reshape(1,1)

In [46]:
d = torch.tensor([0],dtype =torch.float32)

In [47]:
line.weight = torch.nn.Parameter(c)
line.bias =torch.nn.Parameter(d)

In [48]:
# line.weight.shape

torch.Size([1, 1])

## accum grad

In [59]:
variable = torch.tensor([1,2],dtype = torch.float32).reshape(2,1)
target = torch.tensor([0,0],dtype = torch.float32).reshape(2,1)

In [60]:
variable.shape

torch.Size([2, 1])

In [77]:
criterion = nn.MSELoss()
# output = loss()
output = line(variable)
# loss = criterion()

In [78]:
loss= criterion(output,target) /2

In [79]:
loss.backward()

In [80]:
line.weight.grad

tensor([[2.5000]])

In [81]:
variable2 = torch.tensor([3,4],dtype = torch.float32).reshape(2,1)
target2 = torch.tensor([0,0],dtype = torch.float32).reshape(2,1)

In [82]:
output = line(variable2)
loss=criterion(output,target2) /2

In [83]:
loss.backward()

In [84]:
line.weight.grad

tensor([[15.]])

In [85]:
line.zero_grad()

## full batch

In [86]:
variable3 = torch.tensor([1,2,3,4],dtype = torch.float32).reshape(4,1)
target3 = torch.tensor([0,0,0,0],dtype = torch.float32).reshape(4,1)

In [87]:
output = line(variable3)
loss=criterion(output,target3)

In [88]:
loss.backward()

In [89]:
line.weight.grad

tensor([[15.]])